name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al
          git config --global user.email "gh-actions@hackergarten.net"
          git config --global user.name "GH Actions Agent"
          git checkout master
          git commit -am "Adding files"
                  
      - name:  Deploy to mynethome
        # You may pin to the exact commit or the version.
        # uses: c0c1/scp-action@7c13f74869e81c70a71b04ab0a7087dbdee76ab4
        uses: c0c1/scp-action@v1.0
        with:
          # Sorce dir to deploy
          src: .
          # SSH address
          host: mynethome.de
          # Remote dir path
          remote: /var/www/mynethome.de/www/hackergarten
          # SSH Port
          # port: # optional, default is 22
          # SSH User name
          user: mynet
          # Private key
          key: ${{ secrets.MYNET_TOKEN }}    

